- name: Yum installation
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python
    - python-pip
    - git
    - java-1.8.0-openjdk
    - maven

- name: del repository
  yum_repository:
      name: docker-ce
      description: Docker
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo
      state: absent

- name: Add repository
  command:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Complete docker installation
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - docker-ce

- name: Pip-docker dependencies
  pip: 
    name: docker-compose
    state: present

- name: Install docker-machine
  shell: "{{item}}"
  with_items:
    - curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine
    - chmod +x /tmp/docker-machine

- name: Move 
  command: cp /tmp/docker-machine /usr/local/bin/docker-machine