- name: Yum installation
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python
    - python-pip
    - git
    - java-1.8.0-openjdk
    - maven

- name: del repository
  yum_repository:
      name: docker-ce
      description: Docker
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo
      state: absent

- name: Add repository
  command:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Complete docker installation
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - docker-ce

- name: Pip-docker dependencies
  pip: 
    name: docker-compose
    state: present